# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you"ll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you"re sharing your code publicly.

development:
  secret_key_base: 5ff34a1ebf092c39830459350b94d35fd2d2036902f08115baf4f8dd864239f44d7d9f62ec65e3c4c156e45bb2f521a2e7394e0a79451845291bc2d00f1c0614

test:
  secret_key_base: 88fcc04e72eb9164c7bfb07426726414d8503c6634ed800e3fbc7dfa5fa8598829f7bccf4e44ffcd176c27a0312c0a64c88776c8bc741679e4c404007ccd0a0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
